server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 30m
  tomcat:
    connection-timeout: 20000
    keep-alive-timeout: 30000

spring:
  profiles:
    active: prod
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: portfolio_db
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
    enabled: true
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:gouravkrsah78@gmail.com}
    password: ${MAIL_PASSWORD:byqmpgupkojqvzwv}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 30000
          timeout: 30000

app:
  contact:
    email: ${CONTACT_EMAIL:gouravkrsah78@gmail.com}
  keep-alive:
    enabled: true
    interval: 240000  # 4 minutes
    health-check-interval: 600000  # 10 minutes

logging:
  level:
    com.portfolio: INFO
    org.springframework.data.mongodb: WARN
    org.springframework.mail: INFO
    org.springframework.security: WARN
    org.springframework.scheduling: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true
