server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: portfolio_db
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
    enabled: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:gouravkrsah78@gmail.com}
    password: ${MAIL_PASSWORD:byqm pgup kojq vzwv}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

app:
  contact:
    email: ${CONTACT_EMAIL:gouravkrsah78@gmail.com}

logging:
  level:
    com.portfolio: INFO
    org.springframework.data.mongodb: WARN
    org.springframework.mail: INFO
    org.springframework.security: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
