server:
  port: ${PORT:8080}

spring:
  profiles:
    active: prod
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: portfolio_db
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
    enabled: true
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:gouravkrsah78@gmail.com}
    password: ${MAIL_PASSWORD:byqmpgupkojqvzwv}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          connectiontimeout: 30000
          timeout: 30000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

app:
  contact:
    email: ${CONTACT_EMAIL:gouravkrsah78@gmail.com}

logging:
  level:
    com.portfolio: INFO
    org.springframework.data.mongodb: WARN
    org.springframework.mail: INFO
    org.springframework.security: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
