server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/portfolio_db
      database: portfolio_db
  
  security:
    user:
      name: admin
      password: admin123
    enabled: false
  
  mail:
    host: smtp.gmail.com
    port: 465
    username: gouravkrsah78@gmail.com
    password: byqmpgupkojqvzwv
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          connectiontimeout: 30000
          timeout: 30000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

app:
  contact:
    email: gouravkrsah78@gmail.com

logging:
  level:
    com.portfolio: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.boot.autoconfigure.mail: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
